---
- hosts: all
  tasks:
    - include_vars: vars.yaml
    - name: "{{ state }} OpenJDK with Version {{ jdk_version }}"
      apt:
        name: "openjdk-{{ jdk_version }}-jdk"
        state: "{{ state }}"

