- hosts: localhost
  connection: local
  tasks:
    - name: Create a new K8s namespace
      k8s:
        namespace: {{ tenant }}
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: /home/awx/.kube/config.json
    - name: Deploy an application
      k8s:
        namespace: {{ tenant }}
        state: present
        src: files/nginx.yaml
        kubeconfig: /home/awx/.kube/config.json

    - name: Deploy an application svc
      k8s:
        namespace: {{ tenant }}
        state: present
        src: files/nginx-svc.yaml
        kubeconfig: /home/awx/.kube/config.json
    
    - name: Get an existing Service object
      k8s_info:
        api_version: v1
        kind: Service
        name: my-nginx
        namespace: {{ tenant }}
        kubeconfig: /home/awx/.kube/config.json
      register: web_service

    - name: output service info
      debug:
        var: web_service
